routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');})->name('welcome');
Auth::routes();
Route::group(['prefix' => 'student', 'middleware'=>['auth', 'quote', 'path_data', 'breadcrumbs'], 'namespace'=>'web\student'], function()
{
    Route::get('/', 'IndexController@index')->name('student_index');
    Route::group(['prefix' => 'course'],function(){
        Route::get('{course}/lessons', 'CourseController@lessons')->where('course', '[0-9]+')->name('student_lessons');
        Route::get('{course}/{lesson}/pages', 'CourseController@pages')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+'])->name('student_pages');
        Route::get('{course}/{lesson}/{page}/page', 'CourseController@page')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+', 'page'=>'[0-9]+'])->name('student_page');
    });
});
Route::group(['prefix' => 'admin', 'middleware'=>'auth', 'namespace'=>'web\admin'], function()
{
    Route::group(['middleware'=>['role:admin', 'quote']], function()
    {
        Route::get('/', 'IndexController@index')->name('admin_index');
        Route::resource('course_group', 'CourseGroupController');
        Route::resource('course', 'CourseController');
        Route::resource('lesson', 'LessonController');
        Route::resource('page', 'PageController');
        Route::resource('exam', 'ExamController');
        Route::resource('text', 'TextController');
        Route::resource('quote', 'QuoteController');
        Route::group(['prefix' => 'export'], function()
        {
            Route::get('groups', 'ExportController@groups')->name('export_groups');
            Route::get('courses', 'ExportController@courses')->name('export_courses');
            Route::get('lessons', 'ExportController@lessons')->name('export_lessons');
            Route::get('pages', 'ExportController@pages')->name('export_pages');
            Route::get('quotes', 'ExportController@quotes')->name('export_quotes');
            Route::get('texts', 'ExportController@texts')->name('export_texts');
            Route::get('exams', 'ExportController@exams')->name('export_exams');
        });
    });
});

app/Exam.php
<?php
/**
 * Created by PhpStorm.
 * User: Вадим
 * Date: 20.11.2017
 * Time: 20:49
 */

namespace App;
use Illuminate\Database\Eloquent\Model;
class Exam extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'step', 'page_id', 'text_id'];

    public function page(){
        return $this->belongsTo('App\Page');
    }

    public function text(){
        return $this->belongsTo('App\Text');
    }

    public function scopeByPageId($query, $pageId){
        return $query->where('page_id', $pageId);
    }

    public function scopeByFilter($query, \Illuminate\Http\Request $request){
        if($request->has('page_id')) $query->byPageId($request->get('page_id'));
        return $query;
    }

    public function changeText($textId){
        if($textId!=$this->text_id){
            if(isset($this->text_id)) {
                $this->text->exam = 'no';
                $this->text->save();
            }
            $text = Text::find($textId);
            $text->exam = 'yes';
            $text->save();
        }
    }
}

app/Http/Controllers/web/admin/ExamController.php
<?php
namespace app\Http\Controllers\web\admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exam;
use Validator;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('web.admin.exams.index', ['exams'=>Exam::with('page')->byFilter($request)->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('web.admin.exams.create',['texts'=>\App\Text::where('exam', 'no')->get()->pluck('title', 'id')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = array(
            'title'       => 'required',
            'text_id' => 'required|numeric'
        );
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput($request->all());
        } else {
            $exam = new Exam();
            $exam->changeText($request->input('text_id'));
            $exam->fill($request->all());
            $exam->save();
            $request->session()->flash('success', 'Successfully created!');
            return redirect()->route('exam.index', ['page_id'=>$request->get('page_id')]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Exam $exam)
    {
        return view('web.admin.exams.edit', ['exam'=>$exam, 'texts'=>\App\Text::where('exam', 'no')->orWhere('id', $exam->text_id)->get()->pluck('title', 'id')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exam $exam)
    {
        $rules = array(
            'title'       => 'required',
            'text_id' => 'required|numeric'
        );
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput($request->all());
        } else {
            $exam->fill($request->all());
            $exam->changeText($request->input('text_id'));
            $exam->save();
            $request->session()->flash('success', 'Successfully updated !');
            return redirect()->route('exam.index', ['page_id'=>$exam->page_id]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Exam $exam)
    {
        $exam->delete();
        $request->session()->flash('success', 'Successfully deleted!');
        return back();
    }
}

resources/views/web/admin/exams/create.blade.php
@extends('layouts.admin')
@section('content')
<h1>Create a Nerd</h1>

<!-- if there are creation errors, they will show here -->
{{ Html::ul($errors->all(), ['class'=>'alert alert-danger']) }}

{{ Form::open(array('route' => 'exam.store')) }}
{{Form::hidden('page_id', request()->get('page_id'))}}
<div class="form-group">
    {{ Form::label('title', 'Title') }}
    {{ Form::text('title', old('title'), array('class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('text_id', 'Text') }}
    {{ Form::select('text_id', $texts, null, array('class' => 'form-control')) }}
</div>

{{ Form::submit('Save Exam', array('class' => 'btn btn-primary')) }}

{{ Form::close() }}
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        //todo: javascript validation here
    </script>
@endsection

resources/views/web/admin/exams/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Edit "{{ $exam->title }}"</h1>

    <!-- if there are creation errors, they will show here -->
    {{ Html::ul($errors->all(), ['class'=>'alert alert-danger']) }}

    {{ Form::model($exam, array('route' => array('exam.update', $exam->id), 'method' => 'PUT')) }}

    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('text_id', 'Text') }}
        {{ Form::select('text_id', $texts, $exam->text_id, array('class' => 'form-control')) }}
    </div>

    {{ Form::submit('Save Exam', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        //todo: javascript validation here
    </script>
@endsection

resources/views/web/admin/exams/index.blade.php
@extends('layouts.admin')
@section('content')
    <a href="{{route('exam.create')}}?page_id={{request()->get('page_id')}}" type="button" class="btn btn-primary">Create New</a>
    <table class="table table-striped table-hover table-bordered" id="editabledatatable">
        <thead>
        <tr role="row">
            <th>
                Edit
            </th>
            <th>
                Title
            </th>
            <th>
                Step
            </th>
            <th>
                Page
            </th>
            <th>
                &nbsp;
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach ($exams as $exam)
            <tr>
                <td><a class="icon-edit" href='{{route('exam.edit', ['id'=>$exam->id])}}'>&nbsp;</a></td>
                <td>{{$exam->title}}</td>
                <td>{{$exam->step}}</td>
                <td>{{$exam->page->title}}</td>
                <td><a class="icon-remove s-remove-link j-remove-link" href='{{route('exam.destroy', ['exam'=>$exam->id])}}'>&nbsp;</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $exams->appends(request()->input())->links('pagination.default') }}
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        $(document).on('click', '.j-remove-link', function(){
            event.preventDefault();
            if(confirm('A you sure want to remove exam from page?')){
                $('<form>',{
                    'action': $(this).attr('href'),
                    'method': 'POST'
                })
                .append($('<input>', {
                    'name': '_method',
                    'value': 'DELETE',
                    'type': 'hidden'
                }))
                .append('{{ csrf_field() }}')
                .appendTo('body')
                .submit();
            }
        });
    </script>
@endsection