routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');})->name('welcome');
Auth::routes();
Route::group(['prefix' => 'student', 'middleware'=>['auth', 'quote', 'path_data', 'breadcrumbs'], 'namespace'=>'web\student'], function()
{
    Route::get('/', 'IndexController@index')->name('student_index');
    Route::group(['prefix' => 'course'],function(){
        Route::get('{course}/lessons', 'CourseController@lessons')->where('course', '[0-9]+')->name('student_lessons');
        Route::get('{course}/{lesson}/pages', 'CourseController@pages')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+'])->name('student_pages');
        Route::get('{course}/{lesson}/{page}/page', 'CourseController@page')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+', 'page'=>'[0-9]+'])->name('student_page');
    });
});
Route::group(['prefix' => 'admin', 'middleware'=>'auth', 'namespace'=>'web\admin'], function()
{
    Route::group(['middleware'=>['role:admin', 'quote']], function()
    {
        Route::get('/', 'IndexController@index')->name('admin_index');
        Route::resource('course_group', 'CourseGroupController');
        Route::resource('course', 'CourseController');
        Route::resource('lesson', 'LessonController');
        Route::resource('page', 'PageController');
        Route::resource('exam', 'ExamController');
        Route::resource('text', 'TextController');
        Route::resource('quote', 'QuoteController');
        Route::group(['prefix' => 'export'], function()
        {
            Route::get('groups', 'ExportController@groups')->name('export_groups');
            Route::get('courses', 'ExportController@courses')->name('export_courses');
            Route::get('lessons', 'ExportController@lessons')->name('export_lessons');
            Route::get('pages', 'ExportController@pages')->name('export_pages');
            Route::get('quotes', 'ExportController@quotes')->name('export_quotes');
            Route::get('texts', 'ExportController@texts')->name('export_texts');
            Route::get('exams', 'ExportController@exams')->name('export_exams');
        });
    });
});

resources/views/web/admin/courses/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Edit "{{ $course->title }}" Course</h1>

    <!-- if there are creation errors, they will show here -->
    {{ Html::ul($errors->all(), ['class'=>'alert alert-danger']) }}

    {{ Form::model($course, array('route' => array('course.update', $course->id), 'method' => 'PUT')) }}

    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('step', 'Step') }}
        {{ Form::number('step', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('active', 'Active') }}
        {{ Form::text('active', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('lang', 'Lang') }}
        {{ Form::text('description', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('available', 'available') }}
        {{ Form::text('available', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('subscribers', 'subscribers') }}
        {{ Form::text('subscribers', null, array('class' => 'form-control')) }}
    </div>

    {{ Form::submit('Save Course', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        //todo: javascript validation here
    </script>
@endsection

resources/views/web/admin/courses/index.blade.php
@extends('layouts.admin')
@section('content')
<table class="table table-striped table-hover table-bordered" id="editabledatatable">
    <thead>
    <tr role="row">
        <th>
            Edit
        </th>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            Step
        </th>
        <th>
            Active
        </th>
        <th>
            Available
        </th>
        <th>
            Group
        </th>
        <th>
           &nbsp;
        </th>
    </tr>
    </thead>
    <?php

    ?>
    <tbody>
    @foreach ($courses as $course)
        <tr>
            <td><a class="icon-edit" href='{{route('course.edit', ['id'=>$course->id])}}'>&nbsp;</a></td>
            <td>{{$course->title}}</td>
            <td>{{$course->desccription}}</td>
            <td>{{$course->step}}</td>
            <td>{{$course->active}}</td>
            <td>{{$course->available}}</td>
            <td>{{$course->group->title}}</td>
            <td><a class="icon-list-ul" href='{{route('lesson.index')}}?course_id={{$course->id}}'>&nbsp;</a></td>
        </tr>
    @endforeach
    </tbody>
</table>
{{ $courses->appends(request()->input())->links('pagination.default') }}
@endsection