routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');})->name('welcome');
Auth::routes();
Route::group(['prefix' => 'student', 'middleware'=>['auth', 'quote', 'path_data', 'breadcrumbs'], 'namespace'=>'web\student'], function()
{
    Route::get('/', 'IndexController@index')->name('student_index');
    Route::group(['prefix' => 'course'],function(){
        Route::get('{course}/lessons', 'CourseController@lessons')->where('course', '[0-9]+')->name('student_lessons');
        Route::get('{course}/{lesson}/pages', 'CourseController@pages')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+'])->name('student_pages');
        Route::get('{course}/{lesson}/{page}/page', 'CourseController@page')->where(['course'=>'[0-9]+', 'lesson'=>'[0-9]+', 'page'=>'[0-9]+'])->name('student_page');
    });
});
Route::group(['prefix' => 'admin', 'middleware'=>'auth', 'namespace'=>'web\admin'], function()
{
    Route::group(['middleware'=>['role:admin', 'quote']], function()
    {
        Route::get('/', 'IndexController@index')->name('admin_index');
        Route::resource('course_group', 'CourseGroupController');
        Route::resource('course', 'CourseController');
        Route::resource('lesson', 'LessonController');
        Route::resource('page', 'PageController');
        Route::resource('exam', 'ExamController');
        Route::resource('text', 'TextController');
        Route::resource('quote', 'QuoteController');
        Route::group(['prefix' => 'export'], function()
        {
            Route::get('groups', 'ExportController@groups')->name('export_groups');
            Route::get('courses', 'ExportController@courses')->name('export_courses');
            Route::get('lessons', 'ExportController@lessons')->name('export_lessons');
            Route::get('pages', 'ExportController@pages')->name('export_pages');
            Route::get('quotes', 'ExportController@quotes')->name('export_quotes');
            Route::get('texts', 'ExportController@texts')->name('export_texts');
            Route::get('exams', 'ExportController@exams')->name('export_exams');
        });
    });
});

app/Lesson.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Lesson extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'description', 'content', 'step'
    ];

    public function course(){
        return $this->belongsTo('App\Course');
    }

    public function scopeByCourseId($query, $courseId){
        return $query->where('course_id', $courseId);
    }

    public function scopeByFilter($query, \Illuminate\Http\Request &$request){
        if($request->has('course_id')) $query->byCourseId($request->get('course_id'));
        return $query;
    }
}

app/Http/Controllers/web/admin/LessonController.php
<?php
namespace app\Http\Controllers\web\admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Lesson;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('web.admin.lessons.index', ['lessons'=>Lesson::with('course')->byFilter($request)->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('management.business.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {//@todo

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Lesson $lesson)
    {
        return view('web.admin.lessons.edit', ['lesson'=>$lesson]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {//@todo

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Lesson $lesson)
    {
        $lesson->delete();
        $request->session()->flash('success', 'Successfully deleted!');
        return back();
    }
}

resources/views/web/admin/lessons/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1>Edit "{{ $lesson->title }}"</h1>

    <!-- if there are creation errors, they will show here -->
    {{ Html::ul($errors->all(), ['class'=>'alert alert-danger']) }}

    {{ Form::model($lesson, array('route' => array('lesson.update', $lesson->id), 'method' => 'PUT')) }}

    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('description', 'description') }}
        {{ Form::text('description', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('content', 'content') }}
        {{ Form::textarea('content', null, array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('step', 'step') }}
        {{ Form::text('step', null, array('class' => 'form-control')) }}
    </div>

    {{ Form::submit('Save Lesson', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        //todo: javascript validation here
    </script>
@endsection

resources/views/web/admin/lessons/index.blade.php
@extends('layouts.admin')
@section('content')
    <table class="table table-striped table-hover table-bordered" id="editabledatatable">
        <thead>
        <tr role="row">
            <th>
                Edit
            </th>
            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Step
            </th>
            <th>
                Content
            </th>
            <th>
                Course
            </th>
            <th>
                &nbsp;
            </th>
        </tr>
        </thead>
        <?php

        ?>
        <tbody>
        @foreach ($lessons as $lesson)
            <tr>
                <td><a class="icon-edit" href='{{route('lesson.edit', ['id'=>$lesson->id])}}'>&nbsp;</a></td>
                <td>{{$lesson->title}}</td>
                <td>{{$lesson->desccription}}</td>
                <td>{{$lesson->step}}</td>
                <td>{{$lesson->content}}</td>
                <td>{{$lesson->course->title}}</td>
                <td><a class="icon-list-ul" href='{{route('page.index')}}?lesson_id={{$lesson->id}}'>&nbsp;</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $lessons->appends(request()->input())->links('pagination.default') }}
@endsection